#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#  datasource:
#    generate-unique-name: false
#    name: companyTable
#    
#  h2:
#    console:
#      enabled: true
      
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/companyApp
    username: admin
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: CompanyMicroservice

#config server
  profiles:
    active:
    - dev
    
logging:
  level:
    '[org.springframework.jdbc]': debug 

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
        
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0      
info:
  app:
    name:"Company application"