companyservice:
  url: http://companyservice

jobservice:
  url: http://jobservice
  
reviewservice:
  url: http://reviewservice
  
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false  

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: embarkx
    password: embarkx
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: CompanyMicroservice
  rabbitmq:
    host: rabbitMQ
    port: 5672
    username: guest
    password: guest
logging:
  level:
    '[org.springframework.jdbc]': debug 

server:
  port: 8082


management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
      enabled: true        
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0      
info:
  app:
    name:"Company application"