

companyservice:
  url: http://companyservice:8082

jobservice:
  url: http://jobservice:8081
  
reviewservice:
  url: http://reviewservice:8083

eureka:
  client:
    service-url:
      defaultZone: http://service-reg:8761/eureka/  

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/reviewAapp
    username: admin
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ReviewMicroservice 
  rabbitmq:
    host: rabbitMQ
    port: 5672
    username: guest
    password: guest   
logging:
  level:
    '[org.springframework.jdbc]': debug 

server:
  port: 8083
    
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
        
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 
info:
  app:
    name:"Review application"