#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#  datasource:
#    generate-unique-name: false
#    name: reviewTable
#    
#  h2:
#    console:
#      enabled: true
#      
#spring.datasource.url
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reviewAapp
    username: admin
    password: password
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: ReviewMicroservice 
    
logging:
  level:
    '[org.springframework.jdbc]': debug 

server:
  port: 8083
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
        
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0 
info:
  app:
    name:"Review application"